version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:3000"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "8001:80"
    restart: unless-stopped
networks:
  default:
    name: chatio
    