# Crea la imagen de docker para el backend

FROM node:16.20.1-slim as base
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

FROM base as prod
ENV NODE_ENV=production
RUN npm run build
CMD ["npm", "run", "start"]

